// This file is generated by scripts/generate-api-types.mjs. Do not edit it manually.

export interface components {
  schemas: {
    AnalysisCheckMetadata: {
      status: "successful" | "failed" | "timeout" | "cancelled";
      completed_at: string;
      duration_ms: number;
      sources?: Array<string>;
    };
    AnalysisCheckStatus: "queued" | "running" | "successful" | "partial" | "failed";
    AnalysisCreateSchema: {
      domain: string;
    };
    AnalysisError: {
      check: string;
      code: string;
      message: string;
    };
    AnalysisJobSchema: {
      id: string;
      domain: string;
      status: components['schemas']["AnalysisStatus"];
      created_at: string;
      result?: components['schemas']["DomainSchema"] | null;
      error?: components['schemas']["ErrorSchema"] | null;
      progress?: Array<components['schemas']["AnalysisProgressSchema"]>;
    };
    AnalysisMetadata: {
      started_at: string;
      completed_at: string;
      duration_ms: number;
      checks?: Record<string, components['schemas']["AnalysisCheckMetadata"]>;
    };
    AnalysisProgressSchema: {
      check: string;
      status: components['schemas']["AnalysisCheckStatus"];
      duration_ms?: number | null;
    };
    AnalysisStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
    CAARecord: {
      flags: number;
      tag: string;
      value: string;
    };
    DNSSchema: {
      A?: Array<string>;
      AAAA?: Array<string>;
      MX?: Array<components['schemas']["MXRecord"]>;
      TXT?: Array<string>;
      CNAME?: Array<string>;
      NS?: Array<string>;
      SOA?: components['schemas']["SOARecord"] | null;
      CAA?: Array<components['schemas']["CAARecord"]>;
      PTR?: Record<string, string | null>;
      propagation?: components['schemas']["PropagationSchema"] | null;
    };
    DomainSchema: {
      domain: string;
      rdap_server?: string | null;
      status?: Array<string>;
      nameservers?: Array<string>;
      registrar?: string | null;
      registration_date?: string | null;
      expiration_date?: string | null;
      updated_date?: string | null;
      whois_server?: string | null;
      dns?: components['schemas']["DNSSchema"];
      geoip?: Record<string, components['schemas']["GeoIPRecord"]>;
      http?: components['schemas']["HTTPSchema"] | null;
      ssl?: components['schemas']["SSLSchema"] | null;
      ports?: components['schemas']["PortsSchema"] | null;
      latency?: components['schemas']["LatencySchema"] | null;
      metadata?: components['schemas']["AnalysisMetadata"] | null;
      analysis_errors?: Array<components['schemas']["AnalysisError"]>;
    };
    ErrorSchema: {
      code: string;
      message: string;
      details?: Array<Record<string, unknown>> | null;
    };
    GeoIPRecord: {
      ip: string;
      country?: string | null;
      country_code?: string | null;
      region?: string | null;
      city?: string | null;
      zip?: string | null;
      lat?: number | null;
      lon?: number | null;
      timezone?: string | null;
      isp?: string | null;
      org?: string | null;
      asn?: string | null;
      asn_name?: string | null;
    };
    HTTPProbeResult: {
      reachable: boolean;
      status_code?: number | null;
      final_url?: string | null;
      redirect_chain?: Array<string>;
      response_time_ms?: number | null;
      server?: string | null;
      x_powered_by?: string | null;
      via?: string | null;
      content_type?: string | null;
      cache_control?: string | null;
      content_security_policy?: string | null;
      strict_transport_security?: string | null;
      x_frame_options?: string | null;
      x_content_type_options?: string | null;
      referrer_policy?: string | null;
      permissions_policy?: string | null;
    };
    HTTPSchema: {
      http?: components['schemas']["HTTPProbeResult"] | null;
      https?: components['schemas']["HTTPProbeResult"] | null;
    };
    HTTPValidationError: {
      detail?: Array<components['schemas']["ValidationError"]>;
    };
    HealthSchema: {
      status?: "ok";
    };
    LatencyResult: {
      min_ms: number;
      avg_ms: number;
      max_ms: number;
      loss: number;
    };
    LatencySchema: {
      tcp_80?: components['schemas']["LatencyResult"] | null;
      tcp_443?: components['schemas']["LatencyResult"] | null;
    };
    MXRecord: {
      priority: number;
      exchange: string;
    };
    PortResult: {
      port: number;
      open: boolean;
      status: "open" | "closed" | "filtered";
      service?: string | null;
    };
    PortsSchema: {
      results?: Array<components['schemas']["PortResult"]>;
    };
    PropagationSchema: {
      consistent: boolean;
      servers?: Array<components['schemas']["PropagationServerSchema"]>;
    };
    PropagationServerSchema: {
      name: string;
      ip: string;
      A?: Array<string>;
      AAAA?: Array<string>;
      status: "ok" | "timeout" | "error";
    };
    ReadinessSchema: {
      status: "ready" | "not_ready";
      checks: Record<string, "ok" | "unavailable">;
    };
    SOARecord: {
      mname: string;
      rname: string;
      serial: number;
      refresh: number;
      retry: number;
      expire: number;
      minimum: number;
    };
    SSLCertificate: {
      subject?: string | null;
      san?: Array<string>;
      issuer?: string | null;
      issuer_org?: string | null;
      valid_from?: string | null;
      valid_until?: string | null;
      days_remaining?: number | null;
      expired?: boolean;
      serial_number?: string | null;
      fingerprint_sha256?: string | null;
      signature_algorithm?: string | null;
      version?: number | null;
    };
    SSLSchema: {
      valid: boolean;
      error?: string | null;
      protocol?: string | null;
      cipher?: string | null;
      certificate?: components['schemas']["SSLCertificate"] | null;
    };
    ValidationError: {
      loc: Array<string | number>;
      msg: string;
      type: string;
    };
  }
}
