[project]
name = "domain-analyzer"
version = "0.1.0"
description = ""
authors = [
    {name = "ivangor246",email = "ivangor246@gmail.com"}
]

requires-python = ">=3.13"
dynamic = ["dependencies"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "app", from = "src" }
]

[tool.poetry.dependencies]
fastapi = "^0.128.8"
pydantic = "^2.12.5"
pydantic-settings = "^2.12.0"
uvicorn = "^0.40.0"
gunicorn = "^25.0.3"
idna = "^3.11"
httpx = "^0.28.1"
dnspython = "^2.8.0"
cryptography = "^44.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.0"
coverage = "^7.9.1"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["C", "E", "F", "W"]

[tool.ruff.format]
quote-style = "single"
